apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - svc.yaml

# configMapGenerator:
#   - name: csbelastingen-backend-configmap
#     files:
#       - props/props1.properties
#       - props/props2.properties